### PR TITLE
hetsolver: clear solve on completion

### LINKED ISSUE #79: Clear Het Solution When Puzzle Is Solved
The solution is re-solved after all the mirrors despawn which looks weird for the overlay to still be drawn.

Possible fix but idk if it will break anything:

```java
	@Subscribe
	public void onChatMessage(final ChatMessage e)
	{
		if  (e.getMessage().endsWith("violently!"))
		{
			clearSolve(); // "The room shakes violently" message is sent when the seal is broken
		}
	}
	
	@Subscribe
	public void onGameObjectSpawned(final GameObjectSpawned e)
	{
		if (solution == null && e.getGameObject().getId() == NullObjectID.NULL_29733)
		{
			return; // Prevent resolving when solution is null and the "empty" objects are spawned
		}
	}
```

p.s. i think the triangles could look less jarring with a bit of transparency

### PR DESCRIPTION
**Pull request by rdutta**
This effectively clears the overlays (see below) when the seal is broken

before

closes #79

### CODE REVIEW

File: src/main/java/com/duckblade/osrs/toa/features/het/solver/HetSolver.java [hunk 1]
```diff
@@ -84,15 +85,24 @@ public void onGameStateChanged(GameStateChanged e)
...
 	}
 
 	@Subscribe
 	public void onGameObjectSpawned(GameObjectSpawned e)
 	{
+		if (solution == null && e.getGameObject().getId() == NullObjectID.NULL_29733)
+		{
+			return;
+		}
+
```
Comment (LlemonDuck) [inline src/main/java/com/duckblade/osrs/toa/features/het/solver/HetSolver.java:105]: What is this part doing?

File: src/main/java/com/duckblade/osrs/toa/features/het/solver/HetSolver.java [hunk 2]
```diff
@@ -84,15 +85,24 @@ public void onGameStateChanged(GameStateChanged e)
...
+		}
 	}
 
 	@Subscribe
 	public void onGameObjectSpawned(GameObjectSpawned e)
 	{
+		if (solution == null && e.getGameObject().getId() == NullObjectID.NULL_29733)
+		{
+			return;
+		}
```
Comment (LlemonDuck) [inline src/main/java/com/duckblade/osrs/toa/features/het/solver/HetSolver.java:104]: What is this part doing?

Comment (rdutta) [reply src/main/java/com/duckblade/osrs/toa/features/het/solver/HetSolver.java:104]: From what I see it reevaluates the solution every time a gameobject is spawned. The null object is spawned after the seal breaks which triggers resolving the solution and is why the overlay is persisting.
